image: pasdam/qt-builder:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    # - echo http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories
    # - apk add --no-cache lcov
    - make test

build:
  stage: build
  script:
    - make build
